apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  labels:
    type: local
spec:
  storageClassName: "elasticsearch"
  capacity:
    storage: {{ .Values.storage.capacities.elasticsearch }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/data/elastic"
  {{ else }}
  hostPath:
    path: "/opt/clearml/data/elastic_7"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.elasticsearch }}
  storageClassName: "elasticsearch"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv0
  labels:
    type: local
spec:
  storageClassName: "mongo0"
  capacity:
    storage: {{ .Values.storage.capacities.mongo0 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/data/mongo/db"
  {{ else }}
  hostPath:
    path: "/opt/clearml/data/mongo/db"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim0
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.mongo0 }}
  storageClassName: "mongo0"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv1
  labels:
    type: local
spec:
  storageClassName: "mongo1"
  capacity:
    storage: {{ .Values.storage.capacities.mongo1 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/data/mongo/configdb"
  {{ else }}
  hostPath:
    path: "/opt/clearml/data/mongo/configdb"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim1
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.mongo1 }}
  storageClassName: "mongo1"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: local
spec:
  storageClassName: "redis"
  capacity:
    storage: {{ .Values.storage.capacities.redis }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/data/redis"
  {{ else }}
  hostPath:
    path: "/opt/clearml/data/redis"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.redis }}
  storageClassName: "redis"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-pv0
  labels:
    type: local
spec:
  storageClassName: "fileserver0"
  capacity:
    storage: {{ .Values.storage.capacities.fileserver0 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/logs"
  {{ else }}
  hostPath:
    path: "/opt/clearml/logs"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-pv-claim0
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.fileserver0 }}
  storageClassName: "fileserver0"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-pv1
  labels:
    type: local
spec:
  storageClassName: "fileserver1"
  capacity:
    storage: {{ .Values.storage.capacities.fileserver1 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/data/fileserver"
  {{ else }}
  hostPath:
    path: "/opt/clearml/data/fileserver"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-pv-claim1
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.fileserver1 }}
  storageClassName: "fileserver1"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apiserver-pv0
  labels:
    type: local
spec:
  storageClassName: "apiserver0"
  capacity:
    storage: {{ .Values.storage.capacities.apiserver0 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/logs"
  {{ else }}
  hostPath:
    path: "/opt/clearml/logs"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apiserver-pv-claim0
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.apiserver0 }}
  storageClassName: "apiserver0"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apiserver-pv1
  labels:
    type: local
spec:
  storageClassName: "apiserver1"
  capacity:
    storage: {{ .Values.storage.capacities.apiserver1 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/config"
  {{ else }}
  hostPath:
    path: "/opt/clearml/config"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apiserver-pv-claim1
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.apiserver1 }}
  storageClassName: "apiserver1"
  accessModes:
    - ReadWriteOnce