dependencies:
  - name: redis
    version: "~10.9.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: mongodb
    version: "~10.3.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: elasticsearch
    version: "~7.10.1"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
