apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-pv0
  labels:
    type: local
spec:
  storageClassName: "fileserver0"
  capacity:
    storage: {{ .Values.storage.capacities.fileserver0 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/logs"
  {{ else }}
  hostPath:
    path: "/opt/trains/logs"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-pv-claim0
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.fileserver0 }}
  storageClassName: "fileserver0"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-pv1
  labels:
    type: local
spec:
  storageClassName: "fileserver1"
  capacity:
    storage: {{ .Values.storage.capacities.fileserver1 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/data/fileserver"
  {{ else }}
  hostPath:
    path: "/opt/trains/data/fileserver"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-pv-claim1
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.fileserver1 }}
  storageClassName: "fileserver1"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apiserver-pv0
  labels:
    type: local
spec:
  storageClassName: "apiserver0"
  capacity:
    storage: {{ .Values.storage.capacities.apiserver0 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/logs"
  {{ else }}
  hostPath:
    path: "/opt/trains/logs"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apiserver-pv-claim0
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.apiserver0 }}
  storageClassName: "apiserver0"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apiserver-pv1
  labels:
    type: local
spec:
  storageClassName: "apiserver1"
  capacity:
    storage: {{ .Values.storage.capacities.apiserver1 }}
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.use_nfs }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: "{{ .Values.storage.nfs.base_path }}/config"
  {{ else }}
  hostPath:
    path: "/opt/trains/config"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apiserver-pv-claim1
spec:
  resources:
    requests:
      storage: {{ .Values.storage.capacities.apiserver1 }}
  storageClassName: "apiserver1"
  accessModes:
    - ReadWriteOnce
