apiVersion: v2
appVersion: "0.17.0-63"
description: Clearml server Helm chart for Kubernetes
name: clearml-server-chart
version: 0.17.0+1
dependencies:
  - name: redis
    version: "~10.9.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: mongodb
    version: "~10.3.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: elasticsearch
    version: "~7.10.1"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
