clearml:
  nodeSelector: "app: clearml"
  namespace: clearml
  image:
    repository: allegroai/clearml
    tag: 1.0.2
apiserver:
  elasticServiceName: elasticsearch-service
  elasticServicePort: "9200"
  mongoServiceName: mongo-service
  mongoServicePort: "27017"
  redisServiceName: redis
  redisServicePort: "6379"
  prepopulateEnabled: "true"
  prepopulateZipFiles: "/opt/clearml/db-pre-populate"
  prepopulateArtifactsPath: "/mnt/fileserver"
  deploymentType: "Helm"
  configDir: /opt/clearml/config
  volumeMounts:
    - mountPath: /var/log/clearml
      name: apiserver-hostpath0
    - mountPath: /opt/clearml/config
      name: apiserver-hostpath1
  volumes:
    - name: apiserver-hostpath0
      persistentVolumeClaim:
        claimName: apiserver-pv-claim0
    - name: apiserver-hostpath1
      persistentVolumeClaim:
        claimName: apiserver-pv-claim1
  resources:
    requests:
        memory: "150M"
        cpu: "200m"
    limits:
        memory: "150M"
        cpu: "400m"
elasticsearch:
  esJavaOpts: "-Xms2g -Xmx2g"
  esMemoryRequest: "4G"
  esMemoryLimit: "4.6G"
agent:
  numberOfClearmlAgents: 0
  nvidiaGpusPerAgent: 1
  defaultBaseDocker: "nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04"
  dockerMode: true
  agentVersion: "" # if set, it *MUST* include comparison operator (e.g. ">=0.17.2")
  queues: "default" # multiple queues can be specified separated by a space (e.g. "important_jobs default")
  clearmlApiHost: "http://apiserver-service:8008"
  clearmlWebHost: "http://webserver-service"
  clearmlFilesHost: "http://fileserver-service:8081"
  clearmlGitUser: null
  clearmlGitPassword: null
  clearmlAccessKey: null
  clearmlSecretKey: null
  awsAccessKeyId: null
  awsSecretAccessKey: null
  awsDefaultRegion: null
  azureStorageAccount: null
  azureStorageKey: null
  clearmlConfig: |-
    sdk {
    }
agentservices:
  clearmlHostIp: null
  defaultBaseDocker: "ubuntu:18.04"
  agentVersion: ""
  clearmlApiHost: "http://apiserver-service:8008"
  clearmlWebHost: null
  clearmlFilesHost: null
  clearmlGitUser: null
  clearmlGitPassword: null
  clearmlAccessKey: null
  clearmlSecretKey: null
  awsAccessKeyId: null
  awsSecretAccessKey: null
  awsDefaultRegion: null
  azureStorageAccount: null
  azureStorageKey: null
  googleCredentials: null
  clearmlWorkerId: "clearml-services"
  clearmlDockerHostMount: "/opt/clearml/agent:/root/.clearml"
storage:
  use_nfs: false
  nfs:
    base_path: /data/clearml
    server: null
  capacities:
    elasticsearch: 50Gi
    mongo0: 50Gi
    mongo1: 1Gi
    redis: 5Gi
    fileserver0: 5Gi
    fileserver1: 50Gi
    apiserver0: 10Gi
    apiserver1: 1Gi
services:
  webserver:
    nodePort: 30080
    name: webserver-service
  apiserver:
    nodePort: 30008
    name: apiserver-service
  fileserver:
    nodePort: 30081
    name: fileserver-service
  mongo:
    name: mongo-service
  elasticsearch:
    name: elasticsearch-service
  redis:
    name: redis
  agentservices:
    name: agentservices-service
ingress:
    enabled: false
    name: clearml-server-ingress
    annotations: {}
    host: ""
    tls:
        secretName: ""
use_secrets_flexvolume: false
